### ISSUE TITLE
Rabby wallet support

### ISSUE THREAD

**Issue by Chomtana** [voteagora/agora#7]
I am a TechNerd coming over a ticket that wants to use Rabby wallet with https://vote.optimism.io/

He claims that he can't connect his Rabby wallet to https://vote.optimism.io even with WalletConnect.

<img width="494" alt="image" src="https://github.com/voteagora/agora/assets/4103490/be5a9a61-0bac-475f-a489-3aaf16aff03b">

Can someone look at Rabby wallet support?

**Comment by stepandel** [comment]
The support for Rabby wallet has been added in the [rewrite](https://github.com/voteagora/agora-next)
